# Generated by Django 4.2.4 on 2023-08-09 07:56

import apps.users.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.services.get_path_avatar, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), apps.users.services.validate_size_image]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
