# Generated by Django 4.2.4 on 2023-08-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Краткая биография пользователя.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Отображаемое имя пользователя.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Адрес электронной почты пользователя.', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='link',
            field=models.URLField(blank=True, help_text='Ссылка пользователя.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='private_profile',
            field=models.BooleanField(default=False, help_text='Профиль пользователя приватный или нет.'),
        ),
    ]
